### ISSUE TITLE
As a staffer, I'd like the ability to keep my player bit separated from my staff charbit

### ISSUE THREAD

**Issue by fuzzyweapon** [watch-the-skies/watch-the-skies#11]
+needs Osi input
- Need to create some permissions in WHO so that if a staff person has this turned on (implement as a toggle setting) then WHO won't show them puppeting their staff charbit.

This shouldn't be implemented unless there is an easy way for everyone to see what characters are online (if we decide to go that route).  We might need to really think about what we'd pass up by trying to make the character an OOC like representation (like it is on traditional MUs).

**Comment by HeroicLeigh** [comment]
It may be best to have two separate logins, then? Because I like the idea that I can be on a PC and need to quickfix something and not have to go to another window.

**Comment by fuzzyweapon** [comment]
yeah, so I /think/ what I'm thinking is in line with what you're thinking...let me just lay it out (how I think we want it to work) and you tell me where I'm wrong.
1.  Staff can login to their player account.  The player account is not the same name as their staff name.
2.  They have a staff charbit.
3.  They can still use all of their powers on any of their char bits.
4.  But when they are manning a staffbit, people cannot tie the staffbit back to their player account.

Currently, when it comes to the fourth thing here, players could tie staffbits back to their player bit because of `who` showing which charbit you are puppeting.  So my thought is we just hide when staff are puppeting staff bits.

so that's my take for staff, it's not opinionated.  It's just something I'm throwing out for you to give explicit feedback against.

for players....I say we leave i the way it is?  If we allow players to hide their connection to their player from their character...then they're more likely to treat their char bits like player bits and make requests for things like on-grid OOC areas, which is not necessary when we have @ooc.  And on evennia, you page Players, not characters

...so it makes sense to me that we keep things the way they are on the non staff side?

**Comment by HeroicLeigh** [comment]
Okay, so let me be very blunt and simplistic:
You want Staff to be able to hide away who they are at any given time and play in sekrit, but no player is allowed this same ability?

**Comment by fuzzyweapon** [comment]
I don't want this.  I don't care.
Request was the ability to keep staff and player bits separate.  So my question is, what does that mean, and what is our policy on that?  Because that will change code requirements.

It's your call.

**Comment by fuzzyweapon** [comment]
so it's a policy question first...laying it out like this just helps me communicate it more clearly.

**Comment by HeroicLeigh** [comment]
I don't think we should give Staff something like that. If a Staffer explicitly has a need, for some reason, to hide from everyone, they can have a playerbit login independent of their Staff login entirely. But I don't want to craft, from the get-go, an environment that could potentially breed distrust or 'unfairness.' Staff are custodians, not Rulers. We have more powers, but they're used to serve - sort of ideal. 

A Staffer can 'puppet' their PCs, but they will not be hidden as being Staff. If any Staffer wants to keep the two separate, they can create a separate playerbit, but it won't have Staff abilities. I feel like that'd be unfair.

**Comment by fuzzyweapon** [comment]
sounds great!  Thank you!
