### ISSUE TITLE
Disable the idleout timer autokick.

### ISSUE THREAD

**Issue by fuzzyweapon** [watch-the-skies/watch-the-skies#12]

**Comment by HeroicLeigh** [comment]
Please. Priority #1 if possible. The way most of us are, we'll want to stay logged in from the get-go so we can review Public and any discussions.

**Comment by fuzzyweapon** [comment]
Should be fixed.
Also discovered another command that individuals can use called `idle`

This doesn't seem to be documented in the help so far as I can see, but it just uses keepalive signals to keep the client connected.

**Comment by fuzzyweapon** [comment]
Not fixed.
